### ISSUE TITLE
Cannot import themes into Frescobaldi 3.0.0

### ISSUE THREAD

**Issue by papioara** [frescobaldi/frescobaldi-themes#1]
Hi,

First of all thanks a lot for that nice idea. Unfortunately on trying it out, Frescobaldi refused to import the theme.xml file in Settings > Menu > Import always returning the same error message, no matter which theme I try to import:

Kann die Quelldatei nicht lesen: (i.e.: Cannot read source file)
/home/falter/Schreibtisch/base16-ashes.xml
not well-formed (invalid token): line 44, column 91

I opened the xml file with a text editor, and it seems that the culprit is the word/term 'data-pjax-transient'. I have no clue unfortunately what this means, but hopefully this points you in the right direction. Hope you can fix it - or am I missing something?

Thanks for troubleshooting

**Comment by papioara** [comment]
Update: it seems that I solved the issue, but I do not know why. Initially I just downloaded one individual theme (*.xml), saved it in my home folder and tried to import. This Frescobaldi refused to accept. I just downloaded the whole zip file, expanded it and tried to import from the themes folder in there, and now it worked. Why does this function and why does my first approach fail?
Thanks for an explanation...

**Comment by uliska** [comment]
Did you compare the XML file from the two sources?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by papioara** [comment]
Just looked into it, and it shows that the one downloaded first seems to be a html file in spite of its *.xml name. Curious...  Anyway, their code is completely different.

**Comment by uliska** [comment]
This is due to the way Github displays handling files and their display in the website. I've updated the README

**Comment by papioara** [comment]
Thank you! This will help prevent similar problems in the future.
